# Generated by Django 6.0.4 on 2026-04-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('upstream_dependencies', models.TextField()),
                ('downstream_dependencies', models.TextField()),
            ],
        ),
    ]
