# Generated by Django 6.0.4 on 2026-04-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='upstream_dependencies',
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='department_head',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='focus_areas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='github_repo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='project_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='slack_channels',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_wiki',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='downstream_dependencies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
