# Generated by Django 6.0.4 on 2026-04-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_manager_remove_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='upstream_dependencies',
            field=models.TextField(blank=True),
        ),
    ]
