# Generated by Django 6.0.4 on 2026-04-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_upstream_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
